name: Python Dashboard Crypto CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t flask-dashboard-crypto-app .
    
    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name test-app flask-dashboard-crypto-app
        sleep 10
        curl -f http://localhost:5000/health || exit 1
        docker stop test-app